location /msg/ {
  alias /var/www/tauceti/msg/;

  # Must be defined at http level of nginx.conf
	# limit_req_zone $binary_remote_addr zone=limreq:5m rate=4r/s;
  # include /etc/nginx/banlist.conf;

  limit_req zone=limreq burst=5 nodelay;
	limit_req_status 429;

  # Files
  location ~ /msg/files/ {
    deny all;
    return 403;
  }

  # Ban page
  location = /msg/files/text/ban.txt {
    allow all;
    add_header Content-Disposition 'attachment; filename="ban.txt"';
    add_header Content-Type 'text/plain; charset=utf-8';
    add_header Cache-Control 'no-store, no-cache, must-revalidate, max-age=0';
	}

  # Main page
  location = /msg/ {
    index index.php;
    try_files $uri $uri/ /msg/index.php?$args;
  }

  # PHP files
  location ~ \.php$ {
    if ($msg_banlist) {
		  return 302 /msg/files/text/ban.txt;
    }

    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/run/php/php8.3-fpm.sock;

    fastcgi_param SCRIPT_FILENAME $request_filename;
    include fastcgi_params;
  }
}
