version: "0.2"
enabled: true
language: en,ru
files:
  - "**/*"
ignorePaths:
  - ".git/**"
  - "*.ipynb"
dictionaries:
  - en_us
  - ru_ru
allowCompoundWords: true
minWordLength: 2
useGitignore: false
caseSensitive: true
