[Definition]
actionban = sed -i '/^}$/d' /etc/nginx/banlist.conf && printf "    <ip> 1;\n}\n" >> /etc/nginx/banlist.conf && nginx -t && systemctl reload nginx

actionunban = sed -i "/<ip> 1;/d" /etc/nginx/banlist.conf && (grep -q '^}$' /etc/nginx/banlist.conf || echo "}" >> /etc/nginx/banlist.conf) && nginx -t && systemctl reload nginx

[Init]
