[Definition]

banlist = /etc/nginx/banlist.conf
banlog = /var/www/tauceti/msg/files/logs/bans.log

actionban = sed -i '/^}$/d' %(banlist)s && \
            printf "    <ip> 1;\n}\n" >> %(banlist)s && \
            echo "$(date '+%%Y-%%m-%%d %%H:%%M:%%S') - <ip> - B - Banned" >> %(banlog)s && \
            nginx -t && systemctl reload nginx

actionunban = sed -i "/<ip> 1;/d" %(banlist)s && \
              (grep -q '^}$' %(banlist)s || echo "}" >> %(banlist)s) && \
              echo "$(date '+%%Y-%%m-%%d %%H:%%M:%%S') - <ip> - U - Unbanned" >> %(banlog)s && \
              nginx -t && systemctl reload nginx

[Init]
