[msg-protection]
bantime = 8h
findtime = 8m
maxretry = 100

enabled = true
filter = msg-protection
logpath = /var/log/nginx/access.log
action = iptables-multiport[name=msgprotection, port="http,https", protocol=tcp]
