[msg-protection]
bantime = 1h
findtime = 10m
maxretry = 200

enabled = true
filter = msg-protection
logpath = /var/log/nginx/access.log
action = iptables-multiport[name=msgprotection, port="http,https", protocol=tcp]
